name: Deploy new version
on:
  workflow_dispatch:
    inputs:
      workspace:
        description: "Stage to deploy to"
        required: true
        type: choice
        default: Dev
        options: [ Develop, Stage, Production ]
permissions:
  id-token: write
  contents: read
jobs:
  deploy-develop:
    name: Deploy version to Develop
    runs-on: ubuntu-latest
    environment: Develop
    if: ${{ inputs.workspace == 'Develop' }}
    steps:
    - name: Checkout code
      uses: action/checkout @v2
    - name: Develop deployment
      run: echo "Deploying in Develop infrastructure"
  deploy-stage:
    name: Deploy version to QA
    runs-on: ubuntu-latest
    environment: Stage
    if: ${{ inputs.workspace == 'Stage' }}
    steps:
    - name: Checkout code
      uses: action/checkout @v2
    - name: QA deployment
      run: echo "Deploying in QA infrastructure"
  deploy-production:
    name: Deploy version to Production
    runs-on: ubuntu-latest
    environment: Production
    if: ${{ inputs.workspace == 'Production' }}
    steps:
    - name: Checkout code
      uses: action/checkout @v2
    - name: Develop deployment
      run: echo "Deploying in Production infrastructure"
