name: Deploy new version
on:
  workflow_dispatch:
  push:
    branches: [ main ]
permissions:
  id-token: write
  contents: read
jobs:
  deploy-develop:
    name: Deploy version to Develop
    runs-on: ubuntu-latest
    environment: Develop
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Develop deployment
      run: echo "Deploying in Develop infrastructure";
           echo "The secret is ${{ secrets.DEVELOP_SECRET }}";
           echo "The variable is ${{ vars.DEVELOP_VAR }}";
  deploy-stage:
    name: Deploy version to QA
    runs-on: ubuntu-latest
    environment: Stage
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: QA deployment
      run: echo "Deploying in QA infrastructure";
           echo "The secret is ${{ secrets.STAGE_SECRET }}";
           echo "The variable is ${{ vars.STAGE_VAR }}";
  deploy-production:
    name: Deploy version to Production
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Production deployment
      run: echo "Deploying in Production infrastructure"
           echo "The secret is ${{ secrets.PRODCUTION_SECRET }}";
           echo "The variable is ${{ vars.PRODUCTION_VAR }}";
