name: DEHN Risk frontend PR

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]

jobs:
  conventional_commits:
    name: "Conventional commits"
    runs-on: ubuntu-latest
    steps:
      - name: 'Check PR Title'
        run: |
          echo 'Check PR title'
  
  code_formatter:
    name: "Code format (Prettier)"
    runs-on: ubuntu-latest
    needs:
      - conventional_commits
    steps:
      - name: 'Check code format with Prettier'
        run: |
          echo 'Checking code format with Prettier'  
  
  tests: 
    name: "Unitary tests"
    runs-on: ubuntu-latest
    needs:
      - code_formatter
    steps:
      - name: 'Unitary tests before PR'
        run: |
          echo 'Running unitary tests'
