name: DEHN Risk frontend PR

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]

jobs:
  conventional-commits:
    name: "Enforce conventional commits"
    runs-on: ubuntu-latest
    steps:
      - name: 'Check PR Title'
        run: |
          echo 'Check PR title'
  
  code-formatter:
    name: "Check code format with Prettier"
    runs-on: ubuntu-latest
    needs:
      - conventional-commits
    steps:
      - name: 'Check code format with Prettier'
        run: |
          echo 'Checking code format with Prettier'  
  
  tests: 
    name: "Runnig "
    runs-on: ubuntu-latest
    needs:
      - code-formater
    steps:
      - name: 'Unitary tests before PR'
        run: |
          echo 'Running unitary tests'
