name: Pull Request workflow ${GITHUB_ACTOR}
on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
jobs:
  conventional_commits:
    name: "Conventional commits"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: 'Check PR Title'
        run: |
          echo 'Checking PR title'
  code_formatter:
    name: "Code format (Prettier)"
    runs-on: ubuntu-latest
    needs:
      - conventional_commits
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: 'Checking code format with Prettier'
        run: |
          echo 'Checking code format with Prettier'  
  build_and_test: 
    name: "Build and Unit tests"
    runs-on: ubuntu-latest
    needs:
      - code_formatter
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: 'Running Unity Tests for acceptance of PR creation'
        run: |
          echo 'Running Unit Tests'

