name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: Run release-please
      env: 
        DEBUG: release-please*
      uses: googleapis/release-please-action@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 18.17.1
    - name: Update pom.xml
      run: |
        VERSION=$(node -p "require('./package.json').version")
        sed -i 's|<version>.*</version>|<version>$VERSION</version>|' pom.xml

     
